/* ============================================================
   FunEnglish Kids – Data (words, alphabet, vocabulary)
   ============================================================ */

// Alphabet data: letter → { word, emoji, color }
const ALPHABET = [
  { letter: 'A', word: 'Apple',    emoji: '🍎', color: '#ff6b6b' },
  { letter: 'B', word: 'Banana',   emoji: '🍌', color: '#fd9644' },
  { letter: 'C', word: 'Cat',      emoji: '🐱', color: '#feca57' },
  { letter: 'D', word: 'Dog',      emoji: '🐶', color: '#ff9ff3' },
  { letter: 'E', word: 'Elephant', emoji: '🐘', color: '#48dbfb' },
  { letter: 'F', word: 'Fish',     emoji: '🐟', color: '#ff6b6b' },
  { letter: 'G', word: 'Giraffe',  emoji: '🦒', color: '#ffd32a' },
  { letter: 'H', word: 'Horse',    emoji: '🐴', color: '#ff9f43' },
  { letter: 'I', word: 'Igloo',    emoji: '🏔️', color: '#a29bfe' },
  { letter: 'J', word: 'Jellyfish',emoji: '🪼', color: '#fd79a8' },
  { letter: 'K', word: 'Kite',     emoji: '🪁', color: '#6c5ce7' },
  { letter: 'L', word: 'Lion',     emoji: '🦁', color: '#f9ca24' },
  { letter: 'M', word: 'Monkey',   emoji: '🐵', color: '#f0932b' },
  { letter: 'N', word: 'Nest',     emoji: '🪺', color: '#6ab04c' },
  { letter: 'O', word: 'Octopus',  emoji: '🐙', color: '#e84393' },
  { letter: 'P', word: 'Penguin',  emoji: '🐧', color: '#30336b' },
  { letter: 'Q', word: 'Queen',    emoji: '👸', color: '#8e44ad' },
  { letter: 'R', word: 'Rabbit',   emoji: '🐰', color: '#ff6b6b' },
  { letter: 'S', word: 'Snake',    emoji: '🐍', color: '#2ecc71' },
  { letter: 'T', word: 'Tiger',    emoji: '🐯', color: '#e67e22' },
  { letter: 'U', word: 'Umbrella', emoji: '☂️', color: '#1abc9c' },
  { letter: 'V', word: 'Violin',   emoji: '🎻', color: '#8e44ad' },
  { letter: 'W', word: 'Whale',    emoji: '🐋', color: '#3498db' },
  { letter: 'X', word: 'X-ray',    emoji: '🩻', color: '#2c3e50' },
  { letter: 'Y', word: 'Yacht',    emoji: '⛵', color: '#16a085' },
  { letter: 'Z', word: 'Zebra',    emoji: '🦓', color: '#2c3e50' },
];

// Vocabulary categories
const VOCAB = {
  animals: [
    { emoji: '🐶', word: 'Dog',       phonetic: '/dɒɡ/' },
    { emoji: '🐱', word: 'Cat',       phonetic: '/kæt/' },
    { emoji: '🐸', word: 'Frog',      phonetic: '/frɒɡ/' },
    { emoji: '🐧', word: 'Penguin',   phonetic: '/ˈpeŋɡwɪn/' },
    { emoji: '🦁', word: 'Lion',      phonetic: '/ˈlaɪən/' },
    { emoji: '🐘', word: 'Elephant',  phonetic: '/ˈelɪfənt/' },
    { emoji: '🦊', word: 'Fox',       phonetic: '/fɒks/' },
    { emoji: '🐬', word: 'Dolphin',   phonetic: '/ˈdɒlfɪn/' },
    { emoji: '🐻', word: 'Bear',      phonetic: '/beə/' },
    { emoji: '🦒', word: 'Giraffe',   phonetic: '/dʒɪˈrɑːf/' },
    { emoji: '🐯', word: 'Tiger',     phonetic: '/ˈtaɪɡə/' },
    { emoji: '🐙', word: 'Octopus',   phonetic: '/ˈɒktəpəs/' },
  ],
  colors: [
    { emoji: '🔴', word: 'Red',       phonetic: '/red/' },
    { emoji: '🔵', word: 'Blue',      phonetic: '/bluː/' },
    { emoji: '🟡', word: 'Yellow',    phonetic: '/ˈjeloʊ/' },
    { emoji: '🟢', word: 'Green',     phonetic: '/ɡriːn/' },
    { emoji: '🟠', word: 'Orange',    phonetic: '/ˈɒrɪndʒ/' },
    { emoji: '🟣', word: 'Purple',    phonetic: '/ˈpɜːpəl/' },
    { emoji: '⚫', word: 'Black',     phonetic: '/blæk/' },
    { emoji: '⚪', word: 'White',     phonetic: '/waɪt/' },
    { emoji: '🩷', word: 'Pink',      phonetic: '/pɪŋk/' },
    { emoji: '🟤', word: 'Brown',     phonetic: '/braʊn/' },
    { emoji: '🩵', word: 'Cyan',      phonetic: '/ˈsaɪæn/' },
    { emoji: '🪸', word: 'Coral',     phonetic: '/ˈkɒrəl/' },
  ],
  numbers: [
    { emoji: '1️⃣', word: 'One',      phonetic: '/wʌn/' },
    { emoji: '2️⃣', word: 'Two',      phonetic: '/tuː/' },
    { emoji: '3️⃣', word: 'Three',    phonetic: '/θriː/' },
    { emoji: '4️⃣', word: 'Four',     phonetic: '/fɔː/' },
    { emoji: '5️⃣', word: 'Five',     phonetic: '/faɪv/' },
    { emoji: '6️⃣', word: 'Six',      phonetic: '/sɪks/' },
    { emoji: '7️⃣', word: 'Seven',    phonetic: '/ˈsevən/' },
    { emoji: '8️⃣', word: 'Eight',    phonetic: '/eɪt/' },
    { emoji: '9️⃣', word: 'Nine',     phonetic: '/naɪn/' },
    { emoji: '🔟', word: 'Ten',      phonetic: '/ten/' },
    { emoji: '💯', word: 'Hundred',  phonetic: '/ˈhʌndrəd/' },
    { emoji: '♾️', word: 'Infinity', phonetic: '/ɪnˈfɪnɪti/' },
  ],
  fruits: [
    { emoji: '🍎', word: 'Apple',     phonetic: '/ˈæpəl/' },
    { emoji: '🍌', word: 'Banana',    phonetic: '/bəˈnɑːnə/' },
    { emoji: '🍇', word: 'Grapes',    phonetic: '/ɡreɪps/' },
    { emoji: '🍓', word: 'Strawberry',phonetic: '/ˈstrɔːbəri/' },
    { emoji: '🍊', word: 'Orange',    phonetic: '/ˈɒrɪndʒ/' },
    { emoji: '🍋', word: 'Lemon',     phonetic: '/ˈlemən/' },
    { emoji: '🍑', word: 'Peach',     phonetic: '/piːtʃ/' },
    { emoji: '🥭', word: 'Mango',     phonetic: '/ˈmæŋɡoʊ/' },
    { emoji: '🍍', word: 'Pineapple', phonetic: '/ˈpaɪnæpəl/' },
    { emoji: '🍒', word: 'Cherry',    phonetic: '/ˈtʃeri/' },
    { emoji: '🫐', word: 'Blueberry', phonetic: '/ˈbluːberi/' },
    { emoji: '🍉', word: 'Watermelon',phonetic: '/ˈwɔːtəmelən/' },
  ],
  body: [
    { emoji: '👁️', word: 'Eye',       phonetic: '/aɪ/' },
    { emoji: '👂', word: 'Ear',       phonetic: '/ɪə/' },
    { emoji: '👃', word: 'Nose',      phonetic: '/noʊz/' },
    { emoji: '👄', word: 'Mouth',     phonetic: '/maʊθ/' },
    { emoji: '🦷', word: 'Tooth',     phonetic: '/tuːθ/' },
    { emoji: '💪', word: 'Arm',       phonetic: '/ɑːm/' },
    { emoji: '🦵', word: 'Leg',       phonetic: '/leɡ/' },
    { emoji: '🦶', word: 'Foot',      phonetic: '/fʊt/' },
    { emoji: '✋', word: 'Hand',      phonetic: '/hænd/' },
    { emoji: '🫀', word: 'Heart',     phonetic: '/hɑːt/' },
    { emoji: '🧠', word: 'Brain',     phonetic: '/breɪn/' },
    { emoji: '🦴', word: 'Bone',      phonetic: '/boʊn/' },
  ],
  family: [
    { emoji: '👨', word: 'Father',     phonetic: '/ˈfɑːðə/' },
    { emoji: '👩', word: 'Mother',     phonetic: '/ˈmʌðə/' },
    { emoji: '👦', word: 'Brother',    phonetic: '/ˈbrʌðə/' },
    { emoji: '👧', word: 'Sister',     phonetic: '/ˈsɪstə/' },
    { emoji: '👴', word: 'Grandfather',phonetic: '/ˈɡrænfɑːðə/' },
    { emoji: '👵', word: 'Grandmother',phonetic: '/ˈɡrænmʌðə/' },
    { emoji: '👶', word: 'Baby',       phonetic: '/ˈbeɪbi/' },
    { emoji: '👨‍👩‍👧‍👦', word: 'Family',     phonetic: '/ˈfæməli/' },
    { emoji: '🧒', word: 'Child',      phonetic: '/tʃaɪld/' },
    { emoji: '👫', word: 'Friend',     phonetic: '/frend/' },
    { emoji: '🧑', word: 'Person',     phonetic: '/ˈpɜːsən/' },
    { emoji: '👪', word: 'Parents',    phonetic: '/ˈpeərənts/' },
  ],
  school: [
    { emoji: '📖', word: 'Book',       phonetic: '/bʊk/' },
    { emoji: '✏️', word: 'Pencil',     phonetic: '/ˈpensəl/' },
    { emoji: '🖍️', word: 'Crayon',     phonetic: '/ˈkreɪɒn/' },
    { emoji: '📏', word: 'Ruler',      phonetic: '/ˈruːlə/' },
    { emoji: '🎒', word: 'Backpack',   phonetic: '/ˈbækpæk/' },
    { emoji: '📓', word: 'Notebook',   phonetic: '/ˈnoʊtbʊk/' },
    { emoji: '✂️', word: 'Scissors',   phonetic: '/ˈsɪzəz/' },
    { emoji: '🖊️', word: 'Pen',        phonetic: '/pen/' },
    { emoji: '📐', word: 'Triangle',   phonetic: '/ˈtraɪæŋɡəl/' },
    { emoji: '🏫', word: 'School',     phonetic: '/skuːl/' },
    { emoji: '👩‍🏫', word: 'Teacher',    phonetic: '/ˈtiːtʃə/' },
    { emoji: '🪑', word: 'Chair',      phonetic: '/tʃeə/' },
  ],
  food: [
    { emoji: '🍞', word: 'Bread',      phonetic: '/bred/' },
    { emoji: '🧀', word: 'Cheese',     phonetic: '/tʃiːz/' },
    { emoji: '🍚', word: 'Rice',       phonetic: '/raɪs/' },
    { emoji: '🥛', word: 'Milk',       phonetic: '/mɪlk/' },
    { emoji: '🍕', word: 'Pizza',      phonetic: '/ˈpiːtsə/' },
    { emoji: '🍦', word: 'Ice cream',  phonetic: '/aɪs kriːm/' },
    { emoji: '🥚', word: 'Egg',        phonetic: '/eɡ/' },
    { emoji: '🍰', word: 'Cake',       phonetic: '/keɪk/' },
    { emoji: '🥤', word: 'Juice',      phonetic: '/dʒuːs/' },
    { emoji: '💧', word: 'Water',      phonetic: '/ˈwɔːtə/' },
    { emoji: '🍜', word: 'Noodle',     phonetic: '/ˈnuːdəl/' },
    { emoji: '🍗', word: 'Chicken',    phonetic: '/ˈtʃɪkɪn/' },
  ],
  weather: [
    { emoji: '☀️', word: 'Sunny',      phonetic: '/ˈsʌni/' },
    { emoji: '🌧️', word: 'Rainy',      phonetic: '/ˈreɪni/' },
    { emoji: '☁️', word: 'Cloudy',     phonetic: '/ˈklaʊdi/' },
    { emoji: '❄️', word: 'Snowy',      phonetic: '/ˈsnoʊi/' },
    { emoji: '💨', word: 'Windy',      phonetic: '/ˈwɪndi/' },
    { emoji: '⚡', word: 'Thunder',    phonetic: '/ˈθʌndə/' },
    { emoji: '🌈', word: 'Rainbow',    phonetic: '/ˈreɪnboʊ/' },
    { emoji: '🌡️', word: 'Hot',        phonetic: '/hɒt/' },
    { emoji: '🥶', word: 'Cold',       phonetic: '/koʊld/' },
    { emoji: '🌤️', word: 'Weather',    phonetic: '/ˈweðə/' },
    { emoji: '🌫️', word: 'Foggy',      phonetic: '/ˈfɒɡi/' },
    { emoji: '⭐', word: 'Star',       phonetic: '/stɑː/' },
  ],
  clothes: [
    { emoji: '👕', word: 'Shirt',      phonetic: '/ʃɜːt/' },
    { emoji: '👖', word: 'Pants',      phonetic: '/pænts/' },
    { emoji: '👗', word: 'Dress',      phonetic: '/dres/' },
    { emoji: '🧥', word: 'Coat',       phonetic: '/koʊt/' },
    { emoji: '👟', word: 'Shoes',      phonetic: '/ʃuːz/' },
    { emoji: '🧦', word: 'Socks',      phonetic: '/sɒks/' },
    { emoji: '👒', word: 'Hat',        phonetic: '/hæt/' },
    { emoji: '🧤', word: 'Gloves',     phonetic: '/ɡlʌvz/' },
    { emoji: '🧣', word: 'Scarf',      phonetic: '/skɑːf/' },
    { emoji: '👓', word: 'Glasses',    phonetic: '/ˈɡlɑːsɪz/' },
    { emoji: '👢', word: 'Boots',      phonetic: '/buːts/' },
    { emoji: '🎽', word: 'Vest',       phonetic: '/vest/' },
  ],
  vehicles: [
    { emoji: '🚗', word: 'Car',        phonetic: '/kɑː/' },
    { emoji: '🚌', word: 'Bus',        phonetic: '/bʌs/' },
    { emoji: '🚲', word: 'Bicycle',    phonetic: '/ˈbaɪsɪkəl/' },
    { emoji: '✈️', word: 'Airplane',   phonetic: '/ˈeəpleɪn/' },
    { emoji: '🚂', word: 'Train',      phonetic: '/treɪn/' },
    { emoji: '🚀', word: 'Rocket',     phonetic: '/ˈrɒkɪt/' },
    { emoji: '🚁', word: 'Helicopter', phonetic: '/ˈhelɪkɒptə/' },
    { emoji: '🛳️', word: 'Ship',       phonetic: '/ʃɪp/' },
    { emoji: '🏍️', word: 'Motorcycle', phonetic: '/ˈmoʊtəsaɪkəl/' },
    { emoji: '🚒', word: 'Fire truck', phonetic: '/faɪə trʌk/' },
    { emoji: '🚑', word: 'Ambulance',  phonetic: '/ˈæmbjʊləns/' },
    { emoji: '🚜', word: 'Tractor',    phonetic: '/ˈtræktə/' },
  ],
  shapes: [
    { emoji: '⭕', word: 'Circle',     phonetic: '/ˈsɜːkəl/' },
    { emoji: '⬜', word: 'Square',     phonetic: '/skweə/' },
    { emoji: '🔺', word: 'Triangle',   phonetic: '/ˈtraɪæŋɡəl/' },
    { emoji: '⬟', word: 'Pentagon',   phonetic: '/ˈpentəɡən/' },
    { emoji: '💎', word: 'Diamond',    phonetic: '/ˈdaɪmənd/' },
    { emoji: '🟩', word: 'Rectangle',  phonetic: '/ˈrektæŋɡəl/' },
    { emoji: '♥️', word: 'Heart',      phonetic: '/hɑːt/' },
    { emoji: '⭐', word: 'Star',       phonetic: '/stɑː/' },
    { emoji: '🔵', word: 'Oval',       phonetic: '/ˈoʊvəl/' },
    { emoji: '⬡', word: 'Hexagon',    phonetic: '/ˈheksəɡɒn/' },
    { emoji: '🔷', word: 'Rhombus',    phonetic: '/ˈrɒmbəs/' },
    { emoji: '🔲', word: 'Cube',       phonetic: '/kjuːb/' },
  ],
};

// Memory game card pool (emojis + labels)
const MEMORY_CARDS = [
  { emoji: '🦁', label: 'Lion'   },
  { emoji: '🐘', label: 'Elephant'},
  { emoji: '🐬', label: 'Dolphin'},
  { emoji: '🦋', label: 'Butterfly'},
  { emoji: '🐸', label: 'Frog'   },
  { emoji: '🦊', label: 'Fox'    },
  { emoji: '🐧', label: 'Penguin'},
  { emoji: '🐯', label: 'Tiger'  },
  { emoji: '🦒', label: 'Giraffe'},
  { emoji: '🐙', label: 'Octopus'},
  { emoji: '🦓', label: 'Zebra'  },
  { emoji: '🦜', label: 'Parrot' },
];

// Quiz questions pool
const QUIZ_QUESTIONS = [
  { emoji: '🐱', question: 'What animal is this?',     answer: 'Cat',    options: ['Dog', 'Cat', 'Fish', 'Bird'] },
  { emoji: '🍎', question: 'What fruit is this?',      answer: 'Apple',  options: ['Mango', 'Apple', 'Lemon', 'Peach'] },
  { emoji: '🔴', question: 'What color is this?',      answer: 'Red',    options: ['Blue', 'Green', 'Red', 'Yellow'] },
  { emoji: '🐘', question: 'What animal is this?',     answer: 'Elephant',options: ['Elephant', 'Horse', 'Rhino', 'Bear'] },
  { emoji: '🍌', question: 'What fruit is this?',      answer: 'Banana', options: ['Orange', 'Banana', 'Grapes', 'Lemon'] },
  { emoji: '🟡', question: 'What color is this?',      answer: 'Yellow', options: ['Yellow', 'Orange', 'Pink', 'Purple'] },
  { emoji: '🦁', question: 'What animal is this?',     answer: 'Lion',   options: ['Tiger', 'Cheetah', 'Lion', 'Leopard'] },
  { emoji: '🍓', question: 'What fruit is this?',      answer: 'Strawberry', options: ['Cherry', 'Strawberry', 'Raspberry', 'Apple'] },
  { emoji: '🔵', question: 'What color is this?',      answer: 'Blue',   options: ['Blue', 'Cyan', 'Purple', 'Green'] },
  { emoji: '🐸', question: 'What animal is this?',     answer: 'Frog',   options: ['Toad', 'Lizard', 'Frog', 'Turtle'] },
  { emoji: '🍇', question: 'What fruit is this?',      answer: 'Grapes', options: ['Grapes', 'Berries', 'Plums', 'Olives'] },
  { emoji: '🟢', question: 'What color is this?',      answer: 'Green',  options: ['Teal', 'Green', 'Lime', 'Yellow'] },
  { emoji: '🦋', question: 'What insect is this?',     answer: 'Butterfly',options:['Moth', 'Dragonfly', 'Butterfly', 'Bee'] },
  { emoji: '🍊', question: 'What fruit is this?',      answer: 'Orange', options: ['Peach', 'Mango', 'Orange', 'Apricot'] },
  { emoji: '🐶', question: 'What animal is this?',     answer: 'Dog',    options: ['Wolf', 'Dog', 'Fox', 'Bear'] },
  { emoji: '👨', question: 'Who is this?',             answer: 'Father', options: ['Brother', 'Father', 'Uncle', 'Friend'] },
  { emoji: '👩', question: 'Who is this?',             answer: 'Mother', options: ['Mother', 'Sister', 'Teacher', 'Grandmother'] },
  { emoji: '📖', question: 'What school item is this?',answer: 'Book',   options: ['Book', 'Notebook', 'Pencil', 'Ruler'] },
  { emoji: '✏️', question: 'What school item is this?',answer: 'Pencil', options: ['Pen', 'Crayon', 'Pencil', 'Ruler'] },
  { emoji: '🍕', question: 'What food is this?',       answer: 'Pizza',  options: ['Cake', 'Pizza', 'Bread', 'Cheese'] },
  { emoji: '🥛', question: 'What drink is this?',      answer: 'Milk',   options: ['Water', 'Juice', 'Milk', 'Tea'] },
  { emoji: '☀️', question: 'What weather is this?',    answer: 'Sunny',  options: ['Rainy', 'Sunny', 'Cloudy', 'Windy'] },
  { emoji: '🌧️', question: 'What weather is this?',    answer: 'Rainy',  options: ['Snowy', 'Sunny', 'Rainy', 'Foggy'] },
  { emoji: '👕', question: 'What clothing is this?',   answer: 'Shirt',  options: ['Dress', 'Coat', 'Shirt', 'Vest'] },
  { emoji: '👟', question: 'What clothing is this?',   answer: 'Shoes',  options: ['Boots', 'Shoes', 'Socks', 'Gloves'] },
  { emoji: '🚗', question: 'What vehicle is this?',    answer: 'Car',    options: ['Car', 'Bus', 'Train', 'Truck'] },
  { emoji: '✈️', question: 'What vehicle is this?',    answer: 'Airplane',options:['Helicopter', 'Rocket', 'Airplane', 'Ship'] },
  { emoji: '⭕', question: 'What shape is this?',      answer: 'Circle', options: ['Square', 'Circle', 'Triangle', 'Oval'] },
  { emoji: '🔺', question: 'What shape is this?',      answer: 'Triangle',options:['Diamond', 'Star', 'Triangle', 'Pentagon'] },
  { emoji: '🍰', question: 'What food is this?',       answer: 'Cake',   options: ['Bread', 'Cake', 'Cheese', 'Pizza'] },
  { emoji: '🚌', question: 'What vehicle is this?',    answer: 'Bus',    options: ['Car', 'Train', 'Bus', 'Truck'] },
  { emoji: '👒', question: 'What clothing is this?',   answer: 'Hat',    options: ['Scarf', 'Glasses', 'Hat', 'Gloves'] },
  { emoji: '🌈', question: 'What is this?',            answer: 'Rainbow',options: ['Star', 'Rainbow', 'Cloud', 'Sun'] },
  { emoji: '🎒', question: 'What school item is this?',answer: 'Backpack',options:['Bag', 'Backpack', 'Box', 'Basket'] },
];

// Spelling Bee word pool
const SPELLING_WORDS = [
  { emoji: '🐱', word: 'Cat' },
  { emoji: '🐶', word: 'Dog' },
  { emoji: '🐟', word: 'Fish' },
  { emoji: '🦁', word: 'Lion' },
  { emoji: '🐸', word: 'Frog' },
  { emoji: '🍎', word: 'Apple' },
  { emoji: '🍌', word: 'Banana' },
  { emoji: '📖', word: 'Book' },
  { emoji: '⭐', word: 'Star' },
  { emoji: '🚗', word: 'Car' },
  { emoji: '🚌', word: 'Bus' },
  { emoji: '🎒', word: 'Bag' },
  { emoji: '🥛', word: 'Milk' },
  { emoji: '🍞', word: 'Bread' },
  { emoji: '🌧️', word: 'Rain' },
  { emoji: '👒', word: 'Hat' },
  { emoji: '🐻', word: 'Bear' },
  { emoji: '🍕', word: 'Pizza' },
  { emoji: '🐯', word: 'Tiger' },
  { emoji: '🏫', word: 'School' },
  { emoji: '🍰', word: 'Cake' },
  { emoji: '👟', word: 'Shoe' },
  { emoji: '🚂', word: 'Train' },
  { emoji: '🥚', word: 'Egg' },
  { emoji: '🐍', word: 'Snake' },
];

// Word Scramble pool
const SCRAMBLE_WORDS = [
  { emoji: '🐱', word: 'CAT',     hint: 'A pet that says meow' },
  { emoji: '🐶', word: 'DOG',     hint: 'A pet that says woof' },
  { emoji: '🐸', word: 'FROG',    hint: 'A green animal that jumps' },
  { emoji: '🦁', word: 'LION',    hint: 'King of the jungle' },
  { emoji: '🍎', word: 'APPLE',   hint: 'A red fruit' },
  { emoji: '📖', word: 'BOOK',    hint: 'You read this' },
  { emoji: '⭐', word: 'STAR',    hint: 'It shines in the sky at night' },
  { emoji: '🚗', word: 'CAR',     hint: 'A vehicle with 4 wheels' },
  { emoji: '🐟', word: 'FISH',    hint: 'It lives in water' },
  { emoji: '🍌', word: 'BANANA',  hint: 'A yellow fruit monkeys love' },
  { emoji: '🌧️', word: 'RAIN',    hint: 'Water falling from the sky' },
  { emoji: '🍕', word: 'PIZZA',   hint: 'A round Italian food' },
  { emoji: '👒', word: 'HAT',     hint: 'You wear it on your head' },
  { emoji: '🚌', word: 'BUS',     hint: 'A big vehicle for many people' },
  { emoji: '🍰', word: 'CAKE',    hint: 'A sweet dessert for birthdays' },
  { emoji: '🐍', word: 'SNAKE',   hint: 'A long animal without legs' },
  { emoji: '🥛', word: 'MILK',    hint: 'A white drink from cows' },
  { emoji: '🐘', word: 'ELEPHANT',hint: 'The biggest land animal' },
  { emoji: '🌈', word: 'RAINBOW', hint: 'Colorful arc in the sky after rain' },
  { emoji: '🚂', word: 'TRAIN',   hint: 'It rides on rails' },
];

// Listening Game pool
const LISTENING_WORDS = [
  { emoji: '🐱', word: 'Cat',      options: ['🐶', '🐱', '🐸', '🐯'] },
  { emoji: '🐶', word: 'Dog',      options: ['🐱', '🐸', '🐶', '🦊'] },
  { emoji: '🍎', word: 'Apple',    options: ['🍌', '🍎', '🍊', '🍇'] },
  { emoji: '🍌', word: 'Banana',   options: ['🍎', '🍋', '🍌', '🥭'] },
  { emoji: '🐘', word: 'Elephant', options: ['🐘', '🦒', '🐻', '🦁'] },
  { emoji: '🦁', word: 'Lion',     options: ['🐯', '🐱', '🦊', '🦁'] },
  { emoji: '🚗', word: 'Car',      options: ['🚌', '🚂', '🚗', '✈️'] },
  { emoji: '🚌', word: 'Bus',      options: ['🚗', '🚌', '🚂', '🚁'] },
  { emoji: '👕', word: 'Shirt',    options: ['👖', '👗', '👕', '🧥'] },
  { emoji: '👒', word: 'Hat',      options: ['👟', '🧤', '🧣', '👒'] },
  { emoji: '☀️', word: 'Sunny',    options: ['🌧️', '☁️', '☀️', '❄️'] },
  { emoji: '📖', word: 'Book',     options: ['✏️', '📏', '📖', '✂️'] },
  { emoji: '🍕', word: 'Pizza',    options: ['🍕', '🍔', '🍰', '🧀'] },
  { emoji: '🐸', word: 'Frog',     options: ['🐍', '🐸', '🐢', '🦎'] },
  { emoji: '🍓', word: 'Strawberry',options:['🍒', '🍎', '🍓', '🫐'] },
  { emoji: '✈️', word: 'Airplane', options: ['🚁', '🚀', '✈️', '🛳️'] },
  { emoji: '🐯', word: 'Tiger',    options: ['🦁', '🐯', '🐱', '🐆'] },
  { emoji: '⭐', word: 'Star',     options: ['🌙', '⭐', '☀️', '🌈'] },
  { emoji: '🍰', word: 'Cake',     options: ['🍞', '🍰', '🍕', '🧁'] },
  { emoji: '🚂', word: 'Train',    options: ['🚗', '🚌', '🚂', '🚲'] },
];
